### ISSUE TITLE
Are array arbitraries supported?

### ISSUE THREAD

**Issue by ornamentist** [TheSpyder/rescript-fast-check#10]
`fast-check` seems to support an array of arbitraries, arbitrary: https://dubzzz.github.io/fast-check/index.html#array

Are these exported from `rescript-fast-check`?  I may be overlooking them if they are.

**Comment by TheSpyder** [comment]
Almost everything was bound as of the late 2.x fast-check releases, with exceptions noted in comments that were difficult to express in the ReScript type system.

But to keep the API surface manageable, I put array into a `Combinators` submodule. So you have `Combinators.array`, `Combinators.uniqueArray` etc etc.

https://github.com/TheSpyder/rescript-fast-check/blob/4bc5ade8742aee53ad39646006b7af4c5912a8b0/src/Arbitrary.res#L40-L67

The `rescript-fast-check` API structure is based on the `fast-check` usage guide, not the flat API reference. I suppose I should have documented this somewhere 😅 
https://github.com/dubzzz/fast-check/blob/main/packages/fast-check/documentation/Arbitraries.md

**Comment by ornamentist** [comment]
Excellent -- thank you again.

**Comment by TheSpyder** [comment]
Hope this readme update clarifies things a bit 🙂 

https://github.com/TheSpyder/rescript-fast-check/blob/a5c8daca592befbe2f403f0a8bffd85a3fa0755b/README.md#L59-L63

**Comment by ornamentist** [comment]
Yes, thanks. Don't tell anyone but this package is actually fun to use.

**Comment by TheSpyder** [comment]
I'm glad you like it 😁 

I'm fairly involved in the ReScript community and am always happy to help people enjoy the language.
