### ISSUE TITLE
Binding for `scheduler` doesn't seem correct

### ISSUE THREAD

**Issue by timerg** [TheSpyder/rescript-fast-check#5]
Hi, I am using scheduler to create async test. 
When I use scheduler as below, some error are raised like:  `s.schedule is not a function`, or the schedular is simply `null`

```
open Js.Promise
open Property.Async
assert_(
  property1(schedulerr(), s => {
    let result = ref(0)
    Arbitrary.Scheduler.schedule(
      s,
      resolve() |> then_(() => resolve(result := result.contents + 1)),
    ) |> ignore

    Arbitrary.Scheduler.waitAll(s, ()) |> then_(() => resolve(result.contents == 1))
  }),
)

```
I look at the file and found that the binding is not using `schedular` but instead `jsonObject`

https://github.com/TheSpyder/rescript-fast-check/blob/ac00c4c7560197c39763d3e08634d8bb19175f2b/src/Arbitrary.re#L275

I turn to bind my own schedular then the test works fine
```
external scheduler: unit => Arbitrary.arbitrary<Arbitrary.Scheduler.schedulerInstance> = "scheduler"
```
I am using
```
"rescript-fast-check": "^1.0.3"
"@glennsl/bs-jest": "^0.7.0"
```

**Comment by TheSpyder** [comment]
I haven't actually used the scheduler myself so I would totally believe the binding is wrong. It's probably a copy/paste error. I'll double check your suggestion and then release an update!

**Comment by TheSpyder** [comment]
I used your code for the test to make sure this doesn't happen again, thanks for the help :)
